# Generated by Django 2.2.7 on 2019-12-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0002_auto_20191209_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='p_code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, help_text='Auto generated code for person', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='house_number',
            field=models.CharField(help_text='House number / GPS Code', max_length=100),
        ),
    ]
