# Generated by Django 2.2.7 on 2019-12-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0003_auto_20191209_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='passport_pic',
        ),
    ]
