# Generated by Django 2.2.7 on 2019-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0004_remove_personinfo_passport_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='passport_pic',
            field=models.ImageField(default=1, upload_to='passport/%y%m%d/'),
            preserve_default=False,
        ),
    ]
