# Generated by Django 2.2.7 on 2019-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0006_auto_20191209_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='p_code',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
