# Generated by Django 2.2.7 on 2019-12-09 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0007_auto_20191209_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
