# Generated by Django 2.2.7 on 2019-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0009_auto_20191209_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='p_code',
            field=models.CharField(auto_created=True, default=1, help_text='Auto generated code for person', max_length=8),
            preserve_default=False,
        ),
    ]
