# Generated by Django 2.2.7 on 2019-12-09 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0010_personinfo_p_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='p_code',
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
