# Generated by Django 2.2.7 on 2019-12-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_form', '0011_auto_20191209_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='creator',
        ),
    ]
